### ISSUE TITLE
Path Argument error

### ISSUE THREAD

**Issue by Siddhesh30** [basir/node-react-ecommerce#89]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (D:\Project\node-react-ecommerce\frontend\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\index.js:317:13)
    at D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (D:\Project\node-react-ecommerce\frontend\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\index.js:317:13)
    at D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (D:\Project\node-react-ecommerce\frontend\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (D:\Project\node-react-ecommerce\frontend\node_modules\express\lib\router\layer.js:95:5)

**Comment by basir** [comment]
hello there
I just updated the run locally docs. check it now to fix the issue:
https://github.com/basir/node-react-ecommerce#run-locally
